version: "3.5"
services:
  mysql:
    image: mysql:8.0.25
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=academind
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_USER=dyrits
      - MYSQL_PASSWORD=dyrits-password
    ports:
      - "3306:3306"
    expose:
      - 3306

volumes:
  mysql: